Added Hacktoberfest as keyword
nhcarrigan/we-love-hacktoberfest pull request #46
Opened 2020-10-22 19:33 UTC by Vyvy-vi

# Pull Request

Adding phrases for hacktoberfest to the bot [the rest of the team is left out from love :( ]
❤️
## Description:
Same old stuff the bot did for matt, nick, luke, daniel, raven... just with 'hacktoberfest' as keyword(or trigger-word)

## Related Issue: # 45

Closes #45

2020-10-22 19:36 UTC, nhcarrigan requested changes
One nitpick. 

Fix the linting issues as well and this should be good to go.

2020-10-22 19:36 UTC, nhcarrigan commented on src/phrases.ts
> +  "Hacktoberfes team does everything so well!",
```suggestion
  "Hacktoberfest team does everything so well!",
```
Typo.

2020-10-22 19:57 UTC, Vyvy-vi commented on src/phrases.ts
> +  "Hacktoberfes team does everything so well!",
oh wupps

2020-10-23 14:55 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Sorry for the delay!

2020-10-23 14:55 UTC, merged