Added setup instructions
nhcarrigan/we-love-hacktoberfest pull request #63
Opened 2021-03-16 16:53 UTC by adityaraute

# Pull Request

## Description:

 
Instructs the user to help set up their application.

## Related Issue:

Closes #62

2021-03-16 16:55 UTC, nhcarrigan requested changes
Rather than writing a list, let's make this some proper text. [Here's an outdated example](https://github.com/nhcarrigan-archive/Rosalia-Nightsong/blob/main/CONTRIBUTING.md).

2021-03-16 16:55 UTC, nhcarrigan commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`
We should detail the `env` values needed for the project.

2021-03-16 16:58 UTC, adityaraute commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`
So is it okay if I just copy the values from the outdated example?

2021-03-16 17:07 UTC, nhcarrigan commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`
The values in the example are specific to that project. This project uses only one value: `TOKEN`, which is the discord bot token.

(Also noticed I don't have a sample.env so I'll get that added)

2021-03-16 18:30 UTC, nhcarrigan requested changes

2021-03-16 18:30 UTC, nhcarrigan commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`. The value needed for this project will be `DISCORD_TOKEN` : The Discord page will provide you this value. Remember to put this value in quotes.
```suggestion
- Add the retrieved values to `.env`. The value needed for this project will be `TOKEN` : The Discord page will provide you this value. Remember to put this value in quotes.

```
Just `TOKEN`. 🙂

2021-03-16 18:31 UTC, nhcarrigan commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`
Generally the contributing docs on my projects use full paragraphs to allow explanation for each step - I can go ahead and merge this as a list, and revisit later if needed though.

2021-03-17 12:21 UTC, adityaraute commented on CONTRIBUTING.md
> +- Add the retrieved values to `.env`
okay great then

2021-03-17 14:36 UTC, nhcarrigan reviewed
Looks good to me.

2021-03-17 14:36 UTC, nhcarrigan approved these changes

2021-03-17 14:36 UTC, merged

2021-03-17 14:36 UTC, nhcarrigan commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.